# With some help from: https://gist.github.com/dgerosa/2e1f47a39180f39bde848e38243efa94

name: build
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-cz:
    env:
      DIR: src
      FILE: cv_cz
      PREFIX: trojak_
    runs-on: ubuntu-latest
    steps: 
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}
      - run: mv ${{ env.DIR }}/${{ env.FILE }}.pdf ${{ env.DIR }}/${{ env.PREFIX }}${{ env.FILE }}.pdf
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PREFIX }}${{ env.FILE }}.pdf
          path: ${{ env.DIR }}/${{ env.PREFIX }}${{ env.FILE }}.pdf
  build-en:
    env:
      DIR: src
      FILE: cv_en
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}
      - run: mv ${{ env.DIR }}/${{ env.FILE }}.pdf ${{ env.DIR }}/${{ env.PREFIX }}${{ env.FILE }}.pdf
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PREFIX }}${{ env.FILE }}.pdf
          path: ${{ env.DIR }}/${{ env.PREFIX }}${{ env.FILE }}.pdff
  publish:
    needs: [build-en, build-cz]
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: trojak_cv_cz.pdf
          path: public
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: trojak_cv_en.pdf
          path: public
      - uses: actions/upload-pages-artifact@v1
        with:
          path: public
      - uses: actions/deploy-pages@v1
