# With some help from: https://gist.github.com/dgerosa/2e1f47a39180f39bde848e38243efa94

name: build
on:
  push:
    branches:
      - master
jobs:
  build-cz:
    env:
      DIR: src
      FILE: cv_cz
    runs-on: ubuntu-latest
    steps: &build_steps
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILE }}.pdf
          path: ${{ env.DIR }}/${{ env.FILE }}.pdf
  build-en:
    env:
      DIR: src
      FILE: cv_en
    runs-on: ubuntu-latest
    steps:
      *build_steps