name: Build pdf
on:
  push:
    branches: ['*']
  workflow_dispatch:
jobs:
  build-cz:
    env:
      DIR: src
      FILE: trojak_cv_cz
    runs-on: ubuntu-latest
    steps: 
      - name: Set up Git repository
        uses: actions/checkout@v3
      #- name: Compile
      #  uses: dante-ev/latex-action@latest
      #  with:
      #    root_file: ${{ env.FILE }}
      #    working_directory: ${{ env.DIR }}
      - run: echo ahoj > src/${{ env.FILE }}.pdf
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trojak_cz
          path: ${{ env.DIR }}/${{ env.FILE }}.pdf
  build-en:
    env:
      DIR: src
      FILE: trojak_cv_en
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      #- name: Compile
      #  uses: dante-ev/latex-action@latest
      #  with:
      #    root_file: ${{ env.FILE }}
      #    working_directory: ${{ env.DIR }}
      - run: echo ahoj > src/${{ env.FILE }}.pdf
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trojak_cz
          path: ${{ env.DIR }}/${{ env.FILE }}.pdf
