# With some help from: https://gist.github.com/dgerosa/2e1f47a39180f39bde848e38243efa94

name: build
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-cz:
    if: ${{ false }}
    env:
      DIR: src
      FILE: cv_cz
    runs-on: ubuntu-latest
    steps: 
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trojak_${{ env.FILE }}.pdf
          path: ${{ env.DIR }}/${{ env.FILE }}.pdf
  build-en:
    if: ${{ false }}
    env:
      DIR: src
      FILE: cv_en
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trojak_${{ env.FILE }}.pdf
          path: ${{ env.DIR }}/${{ env.FILE }}.pdf
  publish:
    #needs: [build-en, build-cz]
    runs-on: ubuntu-latest
    steps:
      - run: mkdir public
      #- name: Download a single artifact
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: trojak_cv_cz.pdf
      #    path: publish
      #- name: Download a single artifact
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: trojak_cv_en.pdf
      #    path: publish
      - run: echo text | tee public/cv.pdf
      - uses: actions/upload-pages-artifact@v1
        with:
          path: public
      - uses: actions/deploy-pages@v1
