name: Build pdf

env:
  PDF_ARTEF_NAME: trojak_cv

on:
  push:
    branches: ['*']
  workflow_dispatch:
  workflow_call:
    outputs:
      ARTEFACT_NAME:
        description: Name of the artefact
        value: $PDF_ARTEF_NAME

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: src
    strategy:
      matrix:
        file: [trojak_cv_en, trojak_cv_cz]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ matrix.file }}
          working_directory: ${{ env.DIR }}
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PDF_ARTEF_NAME }}
          path: ${{ env.DIR }}/${{ matrix.file }}.pdf
          if-no-files-found: error
