name: Build pdf
on:
  push:
    branches: ['*']
  workflow_dispatch:
jobs:
  build-cz:
    runs-on: ubuntu-latest
    env:
      DIR: src
    strategy:
      matrix:
        file: [trojaj_cv_en.tex, trojak_cv_cz.tex]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ matrix.file }}
          working_directory: ${{ env.DIR }}
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trojak_cv
          path: ${{ env.DIR }}/${{ matrix.file }}.pdf
