name: Deploy to github pages

on:
  workflow_run:
    workflows: ['Build pdf']
    branches: [master]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts from Previous Workflow
        uses: synergy-au/download-workflow-artifacts-action@v1
        with:
          auth-token: ${{ secrets.GITHUB_TOKEN }}
          workflow-run-id: ${{ github.event.workflow_run.id }}
      - run: tree .
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: trojak_cv_cz.pdf
          path: public
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: trojak_cv_en.pdf
          path: public
      - uses: actions/upload-pages-artifact@v1
        with:
          path: public
      - uses: actions/deploy-pages@v1