name: Deploy to github pages

env:
  PDF_ARTEF_NAME: trojak_cv
  INDEX_ARTEF_NAME: index

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-pdf-build:
    uses: ./.github/workflows/build.yaml
  build-index-page:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Build Index page
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: index.html
      - name: Upload index page
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.INDEX_ARTEF_NAME }}
          path: index.html
  publish:
    needs: ['call-pdf-build','build-index-page']
    runs-on: ubuntu-latest
    steps:
      - name: Download pdf-build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PDF_ARTEF_NAME }}
          path: public/
      - name: Dowload index page artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.INDEX_ARTEF_NAME }}
          path: public/
      - name: upload page artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
      - name: Deploy to github pages
        uses: actions/deploy-pages@v1