name: Deploy to github pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-pdf-build:
    uses: ./.github/workflows/build.yaml
  build-index-page:
    runs-on: ubuntu-latest
    steps:
      - name: Build Index page
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: public/index.html
  publish:
    needs: ['call-pdf-build','build-index-page']
    runs-on: ubuntu-latest
    steps:
      - name: Download pdf-build artifact
        uses: actions/download-artifact@v3
        with:
          name: trojak_cv
          path: public/
      - name: upload page artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
      - name: Deploy to github pages
        uses: actions/deploy-pages@v1