name: Deploy to GitHub Pages
on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir public
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          branch: master
          workflow_conclusion: success 
          name: cv_cz.pdf
          path: public 
      - uses: actions/upload-pages-artifact@v1
        with:
          path: public
      - uses: actions/deploy-pages@v1
